Fix error message

diff --git a/adpictl b/adpictl
--- a/adpictl
+++ b/adpictl
@@ -137,7 +137,7 @@ then
   exit 2
 elif [ $status -ne 0 ]
 then
-  echo "Command failure"
+  echo "Command failure" >&2
 fi
 
 exit $status
